#Samuel Andelin, Personal Information Converter
name = input("What is your name?: ")
age = input("What is your age?: ")
favnumber = input("What is your favorite number?: ")
height = input("What is your height in meters?: ")
print("Original Values: ")
print(age)
print(favnumber)
print(height)
height = float(height)
age = int(age)
favnumber = int(favnumber)
print("New Values:")
print(name)
print(age)
print(favnumber)
print(height)
